name: build-app
on: [push]
jobs:
  yarn-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '15'
      - run: yarn install
      - run: yarn build 
      # this might need --frozen-lockfile but it seems to break build
      # TODO add this when we fixed the builds in genreal
